# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './uic_files/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(916, 758)
        MainWindow.setStyleSheet("* {\n"
"    background-color: #202124;\n"
"    color: #fff;\n"
"    border: 0px solid #fff;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 2px solid rgb(211, 79, 115);\n"
"    padding: 10px 17px;\n"
"    color: #D34F73;\n"
"    font-size: 20px;\n"
"    font-family: \'Roboto\', sans-serif;\n"
"    font-weight: 300;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: #06BA63;\n"
"    color: #06BA63;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    width: 15px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background:#D34F73;\n"
"    width: 14px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background:#06BA63;\n"
"    width: 14px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"height: 0px;\n"
"}\n"
"\n"
"\n"
"QScrollBar:up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"          height: 0px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout.addWidget(self.save_btn)
        self.save_as_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_as_btn.setObjectName("save_as_btn")
        self.horizontalLayout.addWidget(self.save_as_btn)
        self.open_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_btn.setObjectName("open_btn")
        self.horizontalLayout.addWidget(self.open_btn)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.current_file_label = QtWidgets.QLineEdit(self.centralwidget)
        self.current_file_label.setStyleSheet("* {\n"
"    color: #9A9FA6;\n"
"}")
        self.current_file_label.setReadOnly(True)
        self.current_file_label.setObjectName("current_file_label")
        self.verticalLayout_2.addWidget(self.current_file_label)
        self.main_layout = QtWidgets.QHBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.edit_panel = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_panel.sizePolicy().hasHeightForWidth())
        self.edit_panel.setSizePolicy(sizePolicy)
        self.edit_panel.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.edit_panel.setFont(font)
        self.edit_panel.setStyleSheet("")
        self.edit_panel.setObjectName("edit_panel")
        self.main_layout.addWidget(self.edit_panel)
        self.render_panel = TextBrowser(self.centralwidget)
        self.render_panel.setStyleSheet("")
        self.render_panel.setObjectName("render_panel")
        self.main_layout.addWidget(self.render_panel)
        self.main_layout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.main_layout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fast Note"))
        self.save_btn.setText(_translate("MainWindow", "SAVE"))
        self.save_as_btn.setText(_translate("MainWindow", "SAVE AS"))
        self.open_btn.setText(_translate("MainWindow", "OPEN"))
        self.pushButton.setText(_translate("MainWindow", "OPEN REMOTE"))
        self.current_file_label.setText(_translate("MainWindow", "unsaved file"))
        self.edit_panel.setPlainText(_translate("MainWindow", "# Привет, Мир!\n"
"\n"
"Эта программа способна отображать файлы формата **.md**\n"
"\n"
"Тут есть поддержка:\n"
"> цитат\n"
"> > вложенных цитат\n"
"\n"
"**различного** *рода* `форматирования`\n"
"\n"
"| таблиц | test       |\n"
"| ---------    | ---------   |\n"
"| 1             | test       |\n"
"| 2             | test       | \n"
"\n"
"## Заголовков\n"
"\n"
"...и **картиночек!**  \n"
"\n"
"![Test Image](https://media.discordapp.net/attachments/745573062279168050/1033651735450886154/unknown.png)"))
        self.render_panel.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
from widgets.TextBrowser import TextBrowser
