# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './uic_files/settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 327)
        Dialog.setStyleSheet("* {\n"
"    background-color: #202124;\n"
"    color: #fff;\n"
"    border: 0px solid #fff;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 2px solid rgb(211, 79, 115);\n"
"    padding: 10px 17px;\n"
"    color: #D34F73;\n"
"    font-size: 20px;\n"
"    font-family: \'Roboto\', sans-serif;\n"
"    font-weight: 300;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: #06BA63;\n"
"    color: #06BA63;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #fff;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settings_layout = QtWidgets.QVBoxLayout()
        self.settings_layout.setObjectName("settings_layout")
        self.verticalLayout.addLayout(self.settings_layout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Settings"))
